# Generated by Django 5.1 on 2026-05-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom commercial')),
                ('dci', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dénomination Commune Internationale')),
                ('forme', models.CharField(blank=True, help_text='Ex: comprimé, sirop, injection', max_length=50, null=True, verbose_name='Forme galénique')),
                ('dosage', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dosage')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat (MAD)")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente (MAD)')),
                ('stock_actuel', models.IntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_minimum', models.IntegerField(default=0, verbose_name='Stock minimum')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('ordonnance_requise', models.BooleanField(default=False, verbose_name='Ordonnance requise')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicaments', to='categories.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
    ]
